name: IZONIL
favicon: null
layout_spectrum: 0.76724
typography_spectrum: 0.53647
title: IZONIL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c1c0c6'
    - '#8f9095'
    - '#373737'
    - '#fefdfd'
  brandStrength: 0.01872857566922903
  lightness: 0.16469959146343172
  saturation: 0.3510691160336137
  rhythmicContrast: 0.9462976260110736
purpose: []
