name: IZONIL
favicon: null
layout_spectrum: 0.75279
typography_spectrum: 0.87071
title: IZONIL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a2c5f'
    - '#4c4c4c'
    - '#d0d0d0'
    - '#696969'
    - '#8a8a8a'
  brandStrength: 0.01872857566922903
  lightness: 0.16469959146343172
  saturation: 0.3510691160336137
  rhythmicContrast: 0.9462976260110736
purpose: []
